<?php
/*
Template Name: 時刻表
Template Post Type: page
*/
?>
<?php get_header(); ?>

<main class="timetable main">
    <div class="mv">
        <img src="<?php echo get_template_directory_uri() ?>/images/contact/mv.png" alt="お問い合わせメインビジュアル">
        <p class="largeHeading eng">Timetable<span>時刻表</span></p>
    </div>

    <div class="timetable__content">
        <h2 class="timetable__content__title" id="kanayama">金山方面より</h2>
        <div class="timetable__content__inner">

            <div class="timetable__content__table">
                <p class="timetable__content__table__title">通常便</p>
                <table class="timetable__content__table__table--half">
                    <thead>
                        <tr>
                            <th>便</th>
                            <th>キャナル発</th>
                            <th>金山駅発</th>
                            <th>六番町発</th>
                            <th>キャナル着</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td></td>
                            <td>8:30</td>
                            <td>8:40</td>
                            <td>8:50</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td></td>
                            <td>9:30</td>
                            <td>9:40</td>
                            <td>9:50</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>10:05</td>
                            <td>10:30</td>
                            <td>10:40</td>
                            <td>10:50</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>11:05</td>
                            <td>11:30</td>
                            <td>11:40</td>
                            <td>11:50</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>12:05</td>
                            <td>12:30</td>
                            <td>12:40</td>
                            <td>12:50</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>13:05</td>
                            <td>13:30</td>
                            <td>13:40</td>
                            <td>13:50</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>14:05</td>
                            <td>14:30</td>
                            <td>14:40</td>
                            <td>14:50</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>15:05</td>
                            <td>15:30</td>
                            <td>15:40</td>
                            <td>15:50</td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td>16:05</td>
                            <td>16:30</td>
                            <td>16:40</td>
                            <td>16:50</td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>17:05</td>
                            <td>17:30</td>
                            <td>17:40</td>
                            <td>17:50</td>
                        </tr>
                        <tr>
                            <td>11</td>
                            <td>18:05</td>
                            <td>18:30</td>
                            <td>18:40</td>
                            <td>18:50</td>
                        </tr>
                        <tr>
                            <td>12</td>
                            <td>19:05</td>
                            <td>19:30</td>
                            <td>19:40</td>
                            <td>19:50</td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td>20:05</td>
                            <td>20:30</td>
                            <td>20:40</td>
                            <td>20:50</td>
                        </tr>
                        <tr>
                            <td>14</td>
                            <td>21:05</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="timetable__content__table">
                <p class="timetable__content__table__title">土日祝増便</p>
                <table class="timetable__content__table__table--half">
                    <thead>
                        <tr>
                            <th>便</th>
                            <th>キャナル発</th>
                            <th>金山駅発</th>
                            <th>六番町発</th>
                            <th>キャナル着</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td></td>
                            <td>8:30</td>
                            <td>8:40</td>
                            <td>8:50</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>9:35</td>
                            <td>10:00</td>
                            <td>10:10</td>
                            <td>10:20</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>10:35</td>
                            <td>11:00</td>
                            <td>11:10</td>
                            <td>11:20</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>11:35</td>
                            <td>12:00</td>
                            <td>12:10</td>
                            <td>12:20</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>12:35</td>
                            <td>13:00</td>
                            <td>13:10</td>
                            <td>13:20</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>13:35</td>
                            <td>14:00</td>
                            <td>14:10</td>
                            <td>14:20</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>14:35</td>
                            <td>15:00</td>
                            <td>15:10</td>
                            <td>15:20</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>15:35</td>
                            <td>16:00</td>
                            <td>16:10</td>
                            <td>16:20</td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td>16:35</td>
                            <td>17:00</td>
                            <td>17:10</td>
                            <td>17:20</td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>17:35</td>
                            <td>18:00</td>
                            <td>18:10</td>
                            <td>18:20</td>
                        </tr>
                        <tr>
                            <td>11</td>
                            <td>18:35</td>
                            <td>19:00</td>
                            <td>19:10</td>
                            <td>19:20</td>
                        </tr>
                        <tr>
                            <td>12</td>
                            <td>19:35</td>
                            <td>20:00</td>
                            <td>20:10</td>
                            <td>20:20</td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td>20:35</td>
                            <td>21:00</td>
                            <td>21:10</td>
                            <td>21:20</td>
                        </tr>
                        <tr>
                            <td>14</td>
                            <td>21:35</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>

                    </tbody>
                </table>
            </div>
        </div>
        <h2 class="timetable__content__title" id="fushimi">名古屋駅、伏見方面より</h2>
        <div class="timetable__content__inner">

            <div class="timetable__content__table">
                <p class="timetable__content__table__title">通常便</p>
                <table>
                    <thead>
                        <tr>
                            <th>便</th>
                            <th>キャナル発</th>
                            <th>名古屋駅発</th>
                            <th>伏見駅発</th>
                            <th>キャナル着</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td></td>
                            <td>8:25</td>
                            <td>8:35</td>
                            <td>8:55</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td></td>
                            <td>9:25</td>
                            <td>9:35</td>
                            <td>9:55</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>10:00</td>
                            <td>10:25</td>
                            <td>10:35</td>
                            <td>10:55</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>11:00</td>
                            <td>11:25</td>
                            <td>11:35</td>
                            <td>11:55</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>12:00</td>
                            <td>12:25</td>
                            <td>12:35</td>
                            <td>12:55</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>13:00</td>
                            <td>13:25</td>
                            <td>13:35</td>
                            <td>13:55</td>
                        </tr>
                        <tr>
                            <td>7</td>
                            <td>14:00</td>
                            <td>14:25</td>
                            <td>14:35</td>
                            <td>14:55</td>
                        </tr>
                        <tr>
                            <td>8</td>
                            <td>15:00</td>
                            <td>15:25</td>
                            <td>15:35</td>
                            <td>15:55</td>
                        </tr>
                        <tr>
                            <td>9</td>
                            <td>16:00</td>
                            <td>16:25</td>
                            <td>16:35</td>
                            <td>16:55</td>
                        </tr>
                        <tr>
                            <td>10</td>
                            <td>17:00</td>
                            <td>17:25</td>
                            <td>17:35</td>
                            <td>17:55</td>
                        </tr>
                        <tr>
                            <td>11</td>
                            <td>18:00</td>
                            <td>18:25</td>
                            <td>18:35</td>
                            <td>18:55</td>
                        </tr>
                        <tr>
                            <td>12</td>
                            <td>19:00</td>
                            <td>19:25</td>
                            <td>19:35</td>
                            <td>19:55</td>
                        </tr>
                        <tr>
                            <td>13</td>
                            <td>20:00</td>
                            <td>20:25</td>
                            <td>20:35</td>
                            <td>20:55</td>
                        </tr>
                        <tr>
                            <td>14</td>
                            <td>21:00</td>
                            <td></td>
                            <td></td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>

<?php get_template_part('/pages/sidenav'); ?>

<?php get_footer(); ?>